version = 0.1

[default.deploy.parameters]
stack_name = "production-todo-list-aws"
resolve_s3 = true
s3_prefix = "production-todo-list-aws"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "Stage=\"production\""
image_repositories = []


[production.global.parameters]
region = "us-east-1"
